name: campusassistant
description: Your Smart Assistant

publish_to: 'none'

version: 1.0.10+21
#change next play store update

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  firebase_analytics: ^12.0.0

  fluttertoast: ^8.2.12
  cached_network_image: ^3.4.1
  file_picker: ^10.3.1
  image_cropper: ^9.1.0
  image_picker: ^1.2.0
  url_launcher: ^6.3.2
  multi_select_flutter: ^4.1.3
  share_plus: ^11.1.0
  youtube_player_flutter: ^9.1.2
  intl: ^0.20.2
#  syncfusion_flutter_pdfviewer: ^30.2.6
  pinch_zoom_release_unzoom: ^2.0.0
  flutter_spinkit: ^5.2.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  dio: ^5.9.0
  flutter_inappwebview: ^6.1.5
  google_fonts: ^6.3.0
  flutter_local_notifications: ^19.4.0
  googleapis_auth: ^2.0.0
  in_app_update: ^4.2.3
  google_mobile_ads: ^6.0.0
  open_filex: ^4.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/categories/
    - assets/data/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf